<html>
    <head>
        <meta charset="utf-8">
        <title>LOGIN OPTIONS</title>
        <link rel="stylesheet" href="JUNKTION.CSS">
    </head>
    <body>
        <div class="headr container-one">
            <header>
                <img src="logo/junktion2.png" class="logo">
                <ul class="menu-bar">
                    <li><a href="JUNKTION.html" title ="This will take you to the Homepage"class="navlinks">HOME</a></li>                                     
                    <li><a href="JUNKTIONCONTACTS.HTML" title="This shows you our contacts"class="navlinks">CONTACT US</a></li>                                        
                    <li><a href="JUNKTIONHELPPAGE.HTML" title="Help page"class="navlinks">HELP</a></li>                                                               
                </ul>
            </header>
        </div>
        <div class="container-one" id="bgpic">
            <div class="container">
                <h1 class="Headings font-4">WHO DO YOU WANT TO LOG IN AS?</h1>
               
                <ul id="logsign">
                    <li><a href="JUNKTIONLOGIN.php" title="Takes you to our User login page"class="logsignlinks">LOG IN AS A CUSTOMER</a></li>
                    <li><a href="ADMINPAGE.php" title="Takes you to our Admin login page"class="logsignlinks">LOG IN AS AN ADMIN</a></li>
                </ul>             
            </div>    
       </div>
       <footer class="cont-footer">
            <div class="row">
                <div class="column">
                    <img src="logo/Juktion3.png" class="logo-footer">
                </div>
                <ul>
                <div class="column" style="padding-top: 120px;padding-right: 10px;">
                    <li><a href="#" Title="Our about us page" id="footer-color">About us</a></li>
                    <li><a href="#" Title="Companies we have partnered with"id="footer-color">Partners</a></li>
                    <li><a href="#" Title="Frequently Asked questions" id="footer-color">FAQ</a></li>
                    <li><a href="#" Title="Cookies"id="footer-color">Cookies</a></li>
                    <li><a href="#" Title="Our privacy terms"id="footer-color">Privacy</a></li>
                </div>
                <div class="column" style="padding-top: 120px; text-align: right;">
                    <li><a href="#" style="color: white;">&copy; 2021 JUNKTION || All rights reserved</a></li>
                </div>
                </ul>
             
            </div>
        </footer>

    </body>
</html>